### ISSUE TITLE
Kuupäeva parsimine vigane

### ISSUE THREAD

**Issue by Marty999** [renekorss/personal-id-code-php#1]
Kuupäeva parsimine on vigane hetke. Aasta arv tekib tulevikus.

näiteks 46402122210 => 2064-02-12     

Oleks vaja arvestada ka esimest numbrit.
Isikukoodi 1. number sisaldab infot nii omaniku soo (paaritu arv – mees, paarisarv – naine) kui ka sünniaasta kahe esimese numbri kohta.

"1", kui 1800...1899. a sündinud mees
"2", kui 1800...1899. a sündinud naine
"3", kui 1900...1999. a sündinud mees
"4", kui 1900...1999. a sündinud naine
"5", kui 2000...2099. a sündinud mees
"6", kui 2000...2099. a sündinud naine
"7", kui 2100...2199. a sündinud mees
"8", kui 2100...2199. a sündinud naine

**Comment by Marty999** [comment]
**getBirthDate** funktsiooni peaks lisama ka **getBirthCentury** ilmselt.

**Comment by renekorss** [comment]
Fixed in [1.0.2](https://github.com/renekorss/personal-id-code-php/releases/tag/1.0.2)
