### ISSUE TITLE
Incorrect hospital ids

### ISSUE THREAD

**Issue by xPaw** [renekorss/personal-id-code-php#4]
https://github.com/renekorss/personal-id-code-php/blob/32f86e5dc043d0be9bb0df7ac29ea437186c4567/src/PersonalIdCode.php#L207-L208

I believe these two should be `11` and `19` rather than `110` and `190` if you follow these codes:

     * 001...010 = Kuressaare Haigla
     * 011...019 = Tartu Ülikooli Naistekliinik, Tartumaa, Tartu
     * 021...220 = Ida-Tallinna Keskhaigla, Pelgulinna sünnitusmaja, Hiiumaa, Keila, Rapla haigla, Loksa haigla

There also appears to be a problem with `020` code, which range does it go into?

**Comment by renekorss** [comment]
Looks like you are correct. I will fix it. 
Our code logic will place `020` under `Tartu Ülikooli Naistekliinik, Tartumaa, Tartu` (after I fix it).
Not sure if there even is `020` possible, These codes are derived by people and there is no official documentation for it.
