### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by jahyvari** [renekorss/personal-id-code-php#6]
Could you add PHP 8 support to this repo?

Composer update fails with a following error after PHP 8 update:

"renekorss/personal-id-code-php[1.1.0, ..., 1.1.2] require php ^7.2 -> your php version (8.0.11) does not satisfy that requirement."

**Comment by renekorss** [comment]
@jahyvari Yes. Will do shortly.

**Comment by renekorss** [comment]
Released in [1.2.0](https://github.com/renekorss/personal-id-code-php/releases/tag/1.2.0).
